version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      envoymesh:
        aliases:
          - server
    environment:
      - SERVICE_NAME=1
    expose:
      - "5678"
    ports:
      - "5678:5678"

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-sidecar_service_1
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
    ports:
      - "7002:80"
      - "7081:8081"

  service2:
    build:
      context: .
      dockerfile: Dockerfile-sidecar_service_2
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
    ports:
      - "7003:80"
      - "7082:8081"

  service3:
    build:
      context: .
      dockerfile: Dockerfile-sidecar_service_3
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service3
    environment:
      - SERVICE_NAME=3
    expose:
      - "80"
    ports:
      - "8002:80"
      - "8081:8081"

  service4:
    build:
      context: .
      dockerfile: Dockerfile-sidecar_service_4
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service4
    environment:
      - SERVICE_NAME=4
    expose:
      - "80"
    ports:
      - "8003:80"
      - "8082:8081"
networks:
  envoymesh: {}
